# Generated by Django 4.1.7 on 2023-03-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='event_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/hackathon'),
        ),
    ]
