# Generated by Django 4.1.7 on 2023-03-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_hackathon_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='allevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, null=True)),
                ('event_name', models.CharField(max_length=50, null=True)),
                ('event_venue', models.CharField(max_length=50, null=True)),
                ('event_info', models.TextField(null=True)),
                ('banner_image', models.ImageField(height_field=20, null=True, upload_to='images', width_field=30)),
                ('team_size', models.IntegerField(null=True)),
                ('deadline', models.DateField(auto_now=True)),
                ('eligibility', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('event_date', models.DateField(auto_now=True)),
                ('info', models.TextField(null=True)),
                ('guidlines', models.TextField()),
                ('rules', models.TextField()),
                ('event_image', models.ImageField(upload_to='images')),
                ('ist_prize', models.IntegerField(null=True)),
                ('second_prize', models.IntegerField(null=True)),
                ('third_prize', models.IntegerField(null=True)),
                ('particpation', models.CharField(max_length=50, null=True)),
                ('contact_name', models.CharField(max_length=50, null=True)),
                ('contact_no', models.IntegerField(null=True)),
                ('reference_url', models.URLField(null=True)),
            ],
        ),
    ]
