# Generated by Django 4.1.7 on 2023-03-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_particpation_allevents_participation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hackathon',
        ),
        migrations.AlterField(
            model_name='allevents',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='allevents',
            name='event_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
