# Generated by Django 4.1.7 on 2023-03-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_delete_hackathon_alter_allevents_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allevents',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='allevents',
            name='event_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
