# Generated by Django 4.1.7 on 2023-04-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_allevents_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allevents',
            name='deadline',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='allevents',
            name='event_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
