# Generated by Django 4.1.7 on 2023-04-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_allevents_deadline_alter_allevents_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allevents',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allevents',
            name='event_date',
            field=models.DateField(),
        ),
    ]
