# Generated by Django 4.1.7 on 2023-04-01 08:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_allevents_deadline_alter_allevents_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allevents',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 200], upload_to='images/'),
        ),
    ]
