# Generated by Django 4.1.7 on 2023-04-01 11:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_allevents_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allevents',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[800, 600], upload_to='images/'),
        ),
    ]
